### ISSUE TITLE
Stopped working altogether

### ISSUE THREAD

**Issue by just-yellow** [paolobasso99/BetterTheatre#14]
It stopped working from an hour to the other, YouTube must have updated something on how the videos are displayed on the page.

Requesting a fix ASAP, since watching YouTube without this extension is awful.

**Comment by paolobasso99** [comment]
Thanks for the info.
I have updated the extension to work with the new YouTube layout.
The updated version is already live on Firefox and it is pending approval for Chrome. It should be available in the next few days.
