### ISSUE TITLE
Fullscreen mode is slightly cut out

### ISSUE THREAD

**Issue by just-yellow** [paolobasso99/BetterTheatre#15]
Fullscreen is slightly cut out if theatre mode is enabled. It behaves normally if not in theatre mode, but still a bit annoying.

[Example](https://i.ibb.co/hBSTBy8/firefox-2023-06-29-22-45-22.png)

**Comment by paolobasso99** [comment]
Fixed.
The update is live for Firefox but it will take a while for Chrome.
Thanks.

**Comment by just-yellow** [comment]
You're the best, tysm! ♥
(I'm using Firefox to watch YT right now... Is there a way for you to send me the extension??)

**Comment by paolobasso99** [comment]
If you want to force the update to happen now on Firefox you can just re-add it [from the store](https://addons.mozilla.org/en-US/firefox/addon/bettertheatre/).

For Chrome the new update must be approved so it will take some time.
I will send you the Chrome extension, but I advise you to just wait a few days: [privatebin](https://privatebin.net/?fa160fcba9d9c4ff#3TNdezbF4VXgRkehXneEMMEorQUmUvZ3zUh2vSMJXYri)

**Comment by just-yellow** [comment]
You are awesome!! Thanks for uploading the .zip
I've removed the old version from my Opera GX (Chromium-based, so Chrome extensions just work there) and loaded the new one and it's working as a charm again.

Idk how open to that you are, but suggest releasing the Chrome extension .zip on GitHub with every new update, or just add it to the README page as a link with a notice.

Thanks for making my (and many other people's!) YouTube experience as it should originally be!! 💛💛

**Comment by just-yellow** [comment]
Oh, I have another suggestion!
Adding an option (or just updating the extension to do it) to remove that [annoying top header](https://i.ibb.co/TTFMxFv/image-2023-06-30-002927683.png) while in theatre mode.

**Comment by paolobasso99** [comment]
> Adding an option (or just updating the extension to do it) to remove that [annoying top header](https://i.ibb.co/TTFMxFv/image-2023-06-30-002927683.png) while in theatre mode.

I don't need this so I won't implement it, open to PRs though.
