### ISSUE TITLE
Stopped working 

### ISSUE THREAD

**Issue by just-yellow** [paolobasso99/BetterTheatre#16]
A few hours ago

**Comment by just-yellow** [comment]
Not sure if you saw my last suggestions too: https://github.com/paolobasso99/BetterTheatre/issues/15

**Comment by just-yellow** [comment]
If you could please send me the updated zip here again I'd be really glad!

Normal YouTube theather mode is pure garbage

**Comment by just-yellow** [comment]
https://github.com/code-charity/youtube/issues/1740

**Comment by just-yellow** [comment]
https://github.com/code-charity/youtube/issues/1740#issuecomment-1684266135

**Comment by just-yellow** [comment]
This should help: https://github.com/code-charity/youtube/issues/1740#issuecomment-1684266135

I used the uBlock Origin filter and it's back to normal ^^

**Comment by paolobasso99** [comment]
Fixed in https://github.com/paolobasso99/BetterTheatre/releases/tag/1.9.0
Updating on stores right now
