### ISSUE TITLE
Doesn't fill browser in fullscreen

### ISSUE THREAD

**Issue by Keith94** [paolobasso99/BetterTheatre#4]
When entering native fullscreen, the video doesn't fill the browser

![image](https://user-images.githubusercontent.com/5490615/114471659-d75c6d80-9ba5-11eb-8b3d-60f401bd05c2.png)

**Comment by paolobasso99** [comment]
Hi, I am going to take a look at this during the weekend.

**Comment by Keith94** [comment]
Thanks! Btw I'm using Edge Canary version on Windows 10

**Comment by paolobasso99** [comment]
Fixed, already updated in Firefox and awaiting for revision in Chrome.
Thank you!
